#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Rosé Pine"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
white = "#e0def4"
black = "#191724"
grey = "#26233a"
blue = "#9ccfd8"
red = "#eb6f92"
yellow = "#f6c177"
orange = "#ebbcba"
green = "#31748f"
purple = "#e0def4"
cyan = "#ebbcba"
magenta = "#c4a7e7"

[color-theme.syntax]
"comment" = "#6e6a86"
"constant" = "$green"
"type" = "#9ccfd8"
"typeAlias" = "#9ccfd8"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "#ebbcba"
"method" = "$green"
"function.method" = "#9ccfd8"
"keyword" = "$green"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$yellow"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
# "label" = "#c4a7e7"
"variable" = "#e0def4"
# "operator" = "#ebbcba"
# "symbol" = ""
# "punctuation" = ""
# "punctuation.special" = ""
# "punctuation.delimiter" = ""
# "text" = "#e0def4"
# "text.literal" = ""
# "text.title" = ""
# "text.uri" = ""
# "text.reference" = ""
# "string.escape" = ""
# "conceal" = ""
# "none" = ""
"tag" = "$blue"
"string.escape" = ""
"punctuation.delimiter" = ""

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#1f1d2e"
"lapce.border" = "#1f1d2e"
"lapce.scroll_bar" = "$grey"

"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"


# tab
"lapce.tab.active.background" = "#6e6a861a"
"lapce.tab.active.foreground" = "#e0def4"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#0000"
"lapce.tab.inactive.foreground" = "#908caa"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = ""


"editor.background" = "$black"    # base
"editor.foreground" = "#e0def4"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528BFF"
"editor.selection" = "#6e6a8633"
"editor.current_line" = "#21202e"
"editor.link" = "$magneta"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#524f6788"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "$black"
"palette.foreground" = "$white"
"palette.current.background" = "$grey"
"palette.current.foreground" = "$white"

"completion.background" = "#26233a"
"completion.current" = "$grey"

"hover.background" = "$black"

"activity.background" = "#191724"
"activity.current" = "$grey"

"panel.background" = "#1f1d2e"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.current.background" = "#26233a80"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.hovered.background" = "#26233a80"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"


"status.background" = "#191724"
"status.foreground" = "#908caa"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#21202e"

"terminal.cursor" = "$white"
"terminal.foreground" = "#e0def4"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"
