name = "rose-pine"
version = "0.2.3"
display-name = "Rosé Pine"
author = "ghishadow"
description = "Soho vibes for Lapce"
repository = "https://github.com/syntacti/rose-pine-lapce"
icon = "icon.png"
color-themes = ["rose-pine.toml", "rose-pine-moon.toml", "rose-pine-dawn.toml"]
